"""empty message

Revision ID: 0a8bc0b99e78
Revises: ccfa5c652c7a
Create Date: 2019-12-16 14:04:47.257983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8bc0b99e78'
down_revision = 'ccfa5c652c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_count',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='rating_count_product_id_fkey'),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], name='rating_count_rating_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'rating_id', name='rating_count_pkey')
    )
    # ### end Alembic commands ###
