"""empty message

Revision ID: ccfa5c652c7a
Revises: 0616d015e2dc
Create Date: 2019-12-15 18:49:16.403004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfa5c652c7a'
down_revision = '0616d015e2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('date_of_sell', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'date_of_sell')
    # ### end Alembic commands ###
